### ISSUE TITLE
split resistor pads are very error-prone

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#101]
![image](https://user-images.githubusercontent.com/48498823/173262070-90118a48-a494-452b-adbd-15668df20b9c.png)

note how resistors flow to one side and leave second part of the pad disconnected!

what is this evil pattern of split pad?! why and how?!

![image](https://user-images.githubusercontent.com/48498823/173262142-eee51252-77d0-45df-9309-c6d875662874.png)

**Comment by rusefillc** [comment]
Affected parts:

R21 R22 R22 R26

**Comment by Qwerty-OFF** [comment]
On the CommonRail board, the shunts were connected incorrectly. A separate conductor must go from the GND pad of the shunt to the chip. As you can see, I made a separate pin for this, but the resistor moved to a larger pad when soldering.

Now the measuring contact is in the middle and the resistor should not move.

![image](https://user-images.githubusercontent.com/4116383/173810489-9b3925b0-6b50-4139-acfb-3decedaa536d.png)

**Comment by mck1117** [comment]
That still has potential for mfg errors. Why not just route a trace to the inside of the resistor?

**Comment by rusefillc** [comment]
For mfg we want two pads of copper, not three not 6.

@Qwerty-OFF point is that kicad would be very confused in terms of DRC if coppers are connected, effectively being connected to GND

I wonder if we need to learn how to kicad this

**Comment by mck1117** [comment]
DRC actually doesn't care. You can have two touching pads no problem. It comes out as a single piece of copper.

**Comment by Qwerty-OFF** [comment]
Figured out how to get KiCAD to connect two pads with different nets in the same footprint without DRC issues. We can applaud the developers of KiCAD for having a special keyword for this.
![image](https://user-images.githubusercontent.com/4116383/173834944-df0f4013-fd46-4458-ba58-23a8b434ebcb.png)

Now definitely no soldering problems
