### ISSUE TITLE
GDI board in 121 case: SWD

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#11]
please have 
1) TC2030 SWD 
2) FTSH-105-01-F-DV-007-K SWD 
3) 0.1" header for the most hard code users

FTSH-105-01-F-DV-007-K the way https://github.com/rusefi/rusefi-hardware/tree/main/wideband-F103 has it on the back is pretty cool but would limit casing, your call depending on tracing considerations

**Comment by rusefillc** [comment]
third SWD option added just to cover all cases

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/155182779-474c7131-bbc0-4ddd-8c7f-8391dd4b4ae6.png)
