### ISSUE TITLE
remove GDI-4ch/hellen-one

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#115]
we have two references to https://github.com/andreika-git/hellen-one

let's keep only the global shared one ``path = hellen-one`` and remove ``path = GDI-4ch/hellen-one``

![image](https://user-images.githubusercontent.com/48498823/177929684-3200072a-ae3d-4016-a50d-4b9093ae213f.png)

**Comment by rusefillc** [comment]
общая копия переехала в папку ext

**Comment by Qwerty-OFF** [comment]
Fixed
