### ISSUE TITLE
shall we use external osc 

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#118]
Does GDI4 board need an external oscillator on F103 for instance for happier CAN connectivity?

**Comment by mck1117** [comment]
GD32 says

![image](https://user-images.githubusercontent.com/568254/178323494-465ac087-fdc4-49af-9a1f-3b436de3834c.png)

STM32F042 says

![image](https://user-images.githubusercontent.com/568254/178323597-9f65aa9f-2cd9-45a5-822c-4660d7455955.png)

STM32F103 says

![image](https://user-images.githubusercontent.com/568254/178323681-b794db1d-380c-4591-a188-9f2f05039852.png)

**Comment by mck1117** [comment]
seems like conventional wisdom on the internet is +-0.25% accuracy for CAN

**Comment by Qwerty-OFF** [comment]
Added in gdi-4ch
