### ISSUE TITLE
WBO, WBOx1: DAC output buffer op-amp gain

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#122]
we shall power DAC with 5v

we need gain of 1 now that we use a 5v DAC

**Comment by Ringenium** [comment]
![image](https://user-images.githubusercontent.com/58686541/182037520-fc56de2b-3766-4e09-bbfc-78b7c189ddaa.png)

Since the DAC of the microcontroller was used, the buffer gain remains the same x1.524
