### ISSUE TITLE
WBO, WBOx1: REF3033 shortcut option

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#123]
добавить (неустанавливаемую) 0R перемычку между VDDA и +3.3V, чтобы мы могли сэкономить на REF3033. А лучще дроссель. какой - можно посмотреть в rusefi-hardware/lambda-x2

**Comment by Ringenium** [comment]
![image](https://user-images.githubusercontent.com/58686541/182037392-67ce34ef-b8b1-42a5-bdee-77a3f9b9791d.png)

Inductance coil L1 is installed
