### ISSUE TITLE
GDI board: dual digital input

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#125]
We still have three available pins

Can we please have two channels of protected digital inputs? Probably old friend 74HC2G17GW https://github.com/rusefi/proteus/issues/1

![image](https://user-images.githubusercontent.com/48498823/179613970-6fd2583b-4ed3-4f29-80e7-2d3ff4df2996.png)

**Comment by Qwerty-OFF** [comment]
Added 4 external channels. Also made jumpers to use the MCU I/O for other purposes.

**Comment by rusefillc** [comment]
looking to have at least one DIN as a HW timer, meaning

PA6 MISO totally cannot touch this one
PA8 kind of can touch but let's not touch to keed firmware compatible between revisions
PB6 LS2 let's flip between LS2 and any of the DIN
PA1 currently VCC2P5

please do at least one of the following changes maybe both if small effort

1) PB6 LS2 let's flip between LS2 and any of the DIN
2) VCC2P5 move to any other A* pin and make PA1 a hardware jumper option between A* and DIN, that way we can leave one of current DIN pins as just a via for future use


speaking of which can we please have a via or test pad on some of DIN* and A* to have an option to repurpose those if needed. Just a couple, via would be better, please use your judgement based on level of effort

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/180446742-564163e1-2627-496a-837c-88f3686b70e6.png)
