### ISSUE TITLE
F103 single: silk

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#126]
please add at least on one side of the PCB
"https://rusefi.com/s/wb"
"F103 single rev3"

**Comment by rusefillc** [comment]
@Ringenium please close if/when silkscreen text

"https://rusefi.com/s/wb"
"F103 single rev3"

is added on any side of the PCB

**Comment by Ringenium** [comment]
![image](https://user-images.githubusercontent.com/58686541/183410490-f5804b83-cfa1-49bb-9077-131a5230b59d.png)

Added silkscreening
