### ISSUE TITLE
Gdi4revB: reset button does not reset

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#129]
looks like reset button does not reset MCU for me at least on one unit

**Comment by Qwerty-OFF** [comment]
Check with a multimeter that there 0V when you press RST button
![image](https://user-images.githubusercontent.com/4116383/183147469-67e10ae7-b84f-4e2e-a743-a79cf9302330.png)

**Comment by rusefillc** [comment]
it was a soldering defect on the first board I've touched - one of button sides was not soldered
