### ISSUE TITLE
GDI4: status LEDs

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#13]
let's have two LEDs available to F103

![image](https://user-images.githubusercontent.com/48498823/148628645-645d2ec9-f616-4674-8880-71f0a67c7c98.png)

![image](https://user-images.githubusercontent.com/48498823/148628648-a514ce9d-6cb4-4084-9d23-a92ff0efefee.png)

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/155183166-ca9d4b3a-9466-4139-9e02-632cfedcc1c0.png)
