### ISSUE TITLE
gdi4-revB: 5v confusion

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#130]
Q1: what is pin11? schematics says nothing, PCB maybe says 5v?

![image](https://user-images.githubusercontent.com/48498823/183256037-80fc2d3f-d212-4b01-a24a-0cec6d1e1a5b.png)

Q2: those 5v pins let's clarify on schematics that those are +5v _outputs_ (assuming those are outputs? while playing we can use as inputs but that's not the primary indented use?)

![image](https://user-images.githubusercontent.com/48498823/183256111-7c2f8479-eb72-4991-bbf7-f7a61c05c286.png)

**Comment by Qwerty-OFF** [comment]
Q1:
![image](https://user-images.githubusercontent.com/4116383/183297585-c26a21a4-eeb9-49e2-96f2-c2e2f82cf609.png)
Q2: how? Like this?
![image](https://user-images.githubusercontent.com/4116383/183297673-2a17f21d-a7b2-4e08-bc65-92571fa08c1d.png)

**Comment by rusefillc** [comment]
супер! 

let's do "output". то же самое для пина 11?

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/rusefi-hardware/assets/4116383/e96b8cde-04ac-436a-9bb8-b68a9583312d)
