### ISSUE TITLE
DIN1 resistors clarification

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#131]
with both R113 and R122 populated do we have DIN1 traced to two different stm32 pins by default?

also R113 state "0" while R122 is yellow without a value not, that's a bit confusing

![image](https://user-images.githubusercontent.com/48498823/183269293-90930dc3-a935-4c0f-b897-f8a490672e7e.png)

**Comment by Qwerty-OFF** [comment]
In this configuration, DIN1 is connected to two different stm32 pins. To connect A0, just remove R122 and put R121, DIN1 will remain connected to PC13 (which does not have a timer).
R122 is a jumper with soldering holes, so it's yellow. In the future we can use yellow resistors like in hellen boards

**Comment by rusefillc** [comment]
Can we add DNP on R122 to make schematics more readable?

Let's add "Use R122 option without R113 for SENT"

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/rusefi-hardware/assets/4116383/b2c85ac7-81c8-466a-8fe7-399d25054eaf)

**Comment by Qwerty-OFF** [comment]
R122 now populated
![image](https://github.com/rusefi/rusefi-hardware/assets/4116383/b622dc4e-5882-4890-943a-e23396762c4a)
