### ISSUE TITLE
F103 WBO BOM

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#133]
need PN for BAT54S

![image](https://user-images.githubusercontent.com/48498823/183313485-229dca30-d4ed-4d6e-a187-65519ee41fce.png)

**Comment by rusefillc** [comment]
мы добавили диоды, потому что защищённый триггер не купить

нужно заменить PN триггера на SN74LVC1G06DBVR C840103

**Comment by Ringenium** [comment]
Исправил
