### ISSUE TITLE
Dual WBO dev comfort - SWD TC2030 and 0.1" header

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#135]
TC2030 is amazing. Dual should have TC2030

the tiny 2x7 connector is hard to purchase and solder, dual WBO should also have plain SWDIO and SWDCLK as boring 0.1" header

**Comment by dron0gus** [comment]
TC2030 is added in Rev1 https://github.com/rusefi/rusefi-hardware/pull/180
