### ISSUE TITLE
GDI4: four channels of analog input

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#14]
let's have for channels of auxiliary analog outputs routed to 121 connector

please use rusEFI typical analog input schematics like on https://github.com/rusefi/hw_microRusEfi with 500K - ish pull-downs and DNP 5v pull-ups

**Comment by rusefillc** [comment]
PA0
PA2
PA3
PA4

**Comment by Qwerty-OFF** [comment]
Which 121 connector pins to use?

**Comment by abelom** [comment]
pins 6 7 8 9

**Comment by Qwerty-OFF** [comment]
Done
