### ISSUE TITLE
GDI4: bleeder resistor for capacitors

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi-hardware#140]
Needs one resistor on each HV rail and 12v rail so that capacitors discharge under 10v in 10 seconds.

**Comment by mck1117** [comment]
Currently, with just the LED and capacitor leakage, it takes 93 seconds for 65v to bleed down below 10v.

**Comment by mck1117** [comment]
For 12v rail (`+Batt_filtered`), recommend 1k ohm to ground, rated for at least 0.5 watt. 

For `Vdrive` rail to `Vdrive_shunt`, recommend 6.8k resistor rated for at least 1 watt.

**Comment by Qwerty-OFF** [comment]
Done. Thanks for the calculations
