### ISSUE TITLE
GDI: replace R38 with 220 ohms

### ISSUE THREAD

**Issue by mck1117** [rusefi/rusefi-hardware#142]
Current 5.1 doesn't do anything useful to damp oscillation on boost converter turn-off, but 220 works very well.

**Comment by mck1117** [comment]
It's just a reduction of EMI. Fully functional with the old value, but new value is quieter.

**Comment by Qwerty-OFF** [comment]
Done
![image](https://github.com/rusefi/rusefi-hardware/assets/4116383/a5fcbbfc-4f65-47b9-9c5b-ffc4a7a9bab8)
