### ISSUE TITLE
GDI4 rev C fabrication quality issues

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#143]
At least two boards got damaged on first injector bench test

@NOx-z reports one board not driving injectors 3 and 4 probably due to poor soldering of D11

![image](https://user-images.githubusercontent.com/48498823/184521687-fc284cc7-e241-4969-a838-97704ba5eeee.png)
![image](https://user-images.githubusercontent.com/48498823/184521694-b15251e4-80f9-490e-875f-8b2a02ad307c.png)

i just had a board make a pop sound while testing injector 4 :( on that board injectors 1, 2 and 3 were working fine. I was using rusEFI Proteus to produce "proper" short test signals and https://github.com/rusefi/rusefi-hardware/releases/tag/20220604_release firmware

**Comment by rusefillc** [comment]
@Qwerty-OFF any ideas what can we make to increase our fabrication chances? would wider pads cause more solder paste? do we have control over solder paste amount?

**Comment by rusefillc** [comment]
Just found a second board with RESET button not working. Looks like JLC has messed up this batch :(

**Comment by rusefillc** [comment]
@mck1117 do "reset" and "boot" buttons work on your board? two of mine needed extra solder for RESET to start working

@NOx-z  do "reset" and "boot" buttons work on your board? two of mine needed extra solder for RESET to start working

**Comment by NOx-z** [comment]
I just poked at it, and my BOOT button completely fell off, then I poked the reset, and it lifted off one leg..

**Comment by rusefillc** [comment]
wow :(

something about solder paste went very wrong on this order. just filed a quality complaint.

**Comment by rusefillc** [comment]
![IMG_20220814_212139](https://user-images.githubusercontent.com/48498823/184576807-fe5aa61a-664b-4bc0-a4f0-d76b070c4286.jpg)
![IMG_20220814_212051](https://user-images.githubusercontent.com/48498823/184576809-c87076ea-4f37-4757-8641-121872db8084.jpg)

**Comment by rusefillc** [comment]
[Noxz](https://app.slack.com/team/UBFRN2SH0)
  [2:52 PM](https://rusefi.slack.com/archives/CFP3QAJCW/p1660589556211969)
I dont really have experience with production settings to answer this next bit.. it seems more an issue with quality control than board layout or components (unless, for instance, the plating/metal of the buttons did not want to adhere to the solder well)







[Matthew Kennedy](https://app.slack.com/team/U80K9BYVD)
  [2:56 PM](https://rusefi.slack.com/archives/CFP3QAJCW/p1660589771313479)
I think it's a fools errand to try and fully self-test power electronics


[Noxz](https://app.slack.com/team/UBFRN2SH0)
  [3:03 PM](https://rusefi.slack.com/archives/CFP3QAJCW/p1660590191173269)
beyond making a jig with pogo pins all over to check continuity autoamtically..


[Matthew Kennedy](https://app.slack.com/team/U80K9BYVD)
  [3:03 PM](https://rusefi.slack.com/archives/CFP3QAJCW/p1660590226097949)
Ever look at a real ECU? Yeah, that's what they do. Test pads all over the place.
[3:03](https://rusefi.slack.com/archives/CFP3QAJCW/p1660590238188559)
but that's what I mean by self test
[3:04](https://rusefi.slack.com/archives/CFP3QAJCW/p1660590249185179)
some things you can self test by adding some analog switches to feed your output back in to the input
[3:04](https://rusefi.slack.com/archives/CFP3QAJCW/p1660590260797269)
but that only works when the penalty for "bad board" is not working, instead of releasing vast magic smoke

**Comment by mck1117** [comment]
Backwards diode on Andrey's rev C

![image](https://user-images.githubusercontent.com/568254/185240667-f947f86a-a50d-4948-8449-0cc140f85ad5.png)

**Comment by mck1117** [comment]
Correct board from the same batch, for reference

![image](https://user-images.githubusercontent.com/568254/185240758-82b5a8d3-3ba5-4e8e-9990-6b5acba164ef.png)

**Comment by rusefillc** [comment]
Wow, that's a third kind of issue on same batch :(

**Comment by mck1117** [comment]
can you forward the images from this thread on to JLC to try and get our coin back on this batch?
