### ISSUE TITLE
quad DDPAK igbt

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#159]
Same as https://github.com/rusefi/rusefi/tree/master/hardware/DDPAK_breakout just four channels and with JLC assembly option

0805 pull-down signal and inline resistors

four input pads/holes diameter = 1.2mm

four output pads/holes diameter = 1.2mm

one GND pad/hole diameter = 2mm

"quad IGBT v 0.1" silkscreen

**Comment by rusefillc** [comment]
See also https://github.com/rusefi/hellen154hyundai/ 

![image](https://user-images.githubusercontent.com/48498823/204658639-cfc3ed08-a1df-4486-99f0-d79bac8d07f5.png)

**Comment by rusefillc** [comment]
@Nadezhda-n please PR into https://github.com/rusefi/rusefi-hardware/tree/main/quad-igbt folder :)

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/205340482-9cf0441c-2b0f-4f69-883b-93b7ea8d336d.png)
![image](https://user-images.githubusercontent.com/99179773/205340645-dc1f3e2a-df22-4229-98fd-a67214dd3fff.png)

**Comment by rusefillc** [comment]
@Nadezhda-n у GND будет дырочка P9?

**Comment by rusefillc** [comment]
@Nadezhda-n R2 в оригинале между R1 и IGBT

а стало 100K снаружи 1K

кажется удобнее и более гибко будет R2 между R1 и IGBT

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/205342519-1a6a093c-931b-43bd-8bbd-ff79a155326c.png)

**Comment by Nadezhda-n** [comment]
> @Nadezhda-n please PR into https://github.com/rusefi/rusefi-hardware/tree/main/quad-igbt folder :)

Посмотри, верно ли тебя поняла :)

**Comment by rusefillc** [comment]
@Nadezhda-n it looks great!

Please add "rusefi.com" silkscreen on the back and push JLC fab files

@Qwerty-OFF please review

**Comment by rusefillc** [comment]
@mck1117 @dron0gus does this need capacitors like https://github.com/andreika-git/hellen-one/issues/207#issuecomment-1336519453 ?

**Comment by dron0gus** [comment]
@rusefillc this capacitor is in feedback circuit, not base

**Comment by rusefillc** [comment]
we have the boards
