### ISSUE TITLE
Улучшить 154 плату

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#160]
https://github.com/rusefi/rusefi-hardware/tree/main/breakout-boards/Breakout_154pin_284617-1-Connector

1) нужно увеличить диаметр маленьких отверстий со нижней половины платы (там, где провода) с 1мм до 1.2мм - не уменьшая ширину дорожек. Для этого видимо ряды 51-60 и 133-154 придётся поставить в шахматном порядке?

2) на шёлкографии нужно подписать сильно больше пинов - в идеале найти способ подписать все пины проводов с обеих сторон и все пины разъёма сзади

3) версию платы на шёлкографии поменять с 0.3 на 0.4

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/206431289-dd7635ce-b5c1-4edc-87a7-7c38997cf990.png)
не очень поняла откуда такие номера в п.1
Если опечатка в числах, то да, надо ставить в шахматном

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/206472879-eb189df3-fc50-4120-aaf0-42e3e65fbd47.png)

**Comment by rusefillc** [comment]
ordered
