### ISSUE TITLE
GDI4: GD32 CAN :(

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#168]
Did we get CAN to work on GD32?

rev A boards have GD32, rev C and later boards would be STM32

but today it would be great to have rev A board working. 

this repo uses 20.rusefi ChibiOS branch https://github.com/rusefi/rusefi-hardware/blob/3e679096ae0831d29b029171dea7ff7ca3f71be4/.gitmodules#L7 not master.wideband

I did cherry pick GD32 CAN commit https://github.com/rusefi/ChibiOS/commits/stable_20.3.x.rusefi are there any other pieces of GD32 CAN drama?

**Comment by dron0gus** [comment]
Should work after this fix. Actually will work without this fix too, but with some tx message lost.

**Comment by rusefillc** [comment]
we are good thank you @dron0gus !
