### ISSUE TITLE
GDI4: SPI with vias

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#17]
can we please have test point vias on all 4 SPI lines?

i guess PB2 for chip select?
![image](https://user-images.githubusercontent.com/48498823/148629911-208a314a-1691-401e-99c3-743d54e00c06.png)

**Comment by Qwerty-OFF** [comment]
Done. PB0 for CS
![image](https://user-images.githubusercontent.com/4116383/155221653-d82b599e-698a-40e4-974d-b5277b18ded0.png)
Another pins used:
![image](https://user-images.githubusercontent.com/4116383/155221917-3e6fe77a-9b01-46c7-bf35-a5834fa7ba8d.png)
