### ISSUE TITLE
wbo dual: C10 & C35

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#172]
"C35, C10 - recalculate"

**Comment by rusefillc** [comment]
@dron0gus is single channel board affected?

**Comment by rusefillc** [comment]
10nf C15195 has helped somewhat

![image](https://user-images.githubusercontent.com/48498823/218160000-1d58a3cf-f022-4df3-b48b-203ff4b14e54.png)

**Comment by rusefillc** [comment]
Alex says

Туда лучше всего где-то 1-2.2нФ поставить в следующей версии. Постоянная времени цепи т=rc 100000Ом * 0.0000000022Ф = 0,00022с. Или 0.22мс. при периоде 2.5мс.

**Comment by dron0gus** [comment]
Replaced with 1nF on Rev1 https://github.com/rusefi/rusefi-hardware/pull/180
