### ISSUE TITLE
TLE9104SH breakout board

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#186]
Need a test PCB for https://www.infineon.com/dgdl/Infineon-TLE9104SH-DataSheet-v01_31-EN.pdf?fileId=5546d462766cbe86017676144d76581b

Same idea as https://github.com/rusefi/hw_modular/tree/master/TLE8110ED_breakout_board - just one component in the middle, nice silk and all the needed holes for 2.54"

PS: actually
A capacitor between pins VDD to GND and VIO to GND is recommended - please use 0805

Also 0805 0R for "EN pin has to be kept high to VIO"

**Comment by mck1117** [comment]
https://github.com/mck1117/tle9104-breakout

**Comment by mck1117** [comment]
I fabbed one and it works. RusEFI driver is implemented.
