### ISSUE TITLE
WBO-F103: silkscreen

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#19]
We need silkscreen for all pins. Looks like back side would be perfect?

while we are on that subject we can use some board name on the back maybe even with some URL maybe even https://github.com/s/wb

**Comment by rusefillc** [comment]
@blundar I am not sure if I am doing anything wrong but I do no see silk on back of PCB :(

![image](https://user-images.githubusercontent.com/48498823/149260284-1c9508eb-424a-425f-a3f0-1238eabcf3ba.png)

can you plz paste a screenshot of how it looks on your end?

**Comment by dron0gus** [comment]
![Screenshot from 2022-04-11 00-13-13](https://user-images.githubusercontent.com/28624689/162640104-40c30eb3-4fcf-4d96-9e47-529485b3c319.png)
How it looks like after https://github.com/rusefi/rusefi-hardware/pull/60 .
