### ISSUE TITLE
JLC to solder 2x2 UART and 1x6 headers

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#196]
let's add J1 into BOM:
4 2.54mm
https://jlcpcb.com/partdetail/boomele_boom_Precision_elec-C66690/C66690
C66690

and similar J4 1x6

![WhatsApp Image 2023-05-13 at 10 45 46](https://github.com/rusefi/rusefi-hardware/assets/48498823/481f4de1-1f9a-4ada-a35d-399919d02a17)

**Comment by Qwerty-OFF** [comment]
Done

**Comment by rusefillc** [comment]
припаял ещё пять пинов - за три цента пусть лучше JLC

![image](https://github.com/rusefi/rusefi-hardware/assets/48498823/75ca4807-9178-427a-91c0-5d2e8061fe78)

**Comment by Qwerty-OFF** [comment]
Сделал его шестиконтактным чтобы не платить за еще один extended.
![image](https://github.com/rusefi/rusefi-hardware/assets/4116383/6649fbef-fabd-4c5f-8130-a30f032aa89f)
