### ISSUE TITLE
remove IN_PUMP2, rename IN_PUMP1

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#198]
Follow-up for https://github.com/rusefi/rusefi-hardware/issues/197

* IN_PUMP2 makes no sense please remove it
* please rename IN_PUMP1 to just "IN_PUMP"
* we need a blue comment on the board: "This board could either drive 4 injectors and one SCV/PUMP, or 6 injectors. In 6 injectors mode we are limited at 120 degrees injection angle"

Relevant jumpers
* R87
* R37 and R41
* R88/R89

R37, R87 is DNP for 6ch mode

**Comment by mck1117** [comment]
That text comment should also say which jumpers to move to be used in 6ch vs 4+1 mode

**Comment by Qwerty-OFF** [comment]
Done
![image](https://github.com/rusefi/rusefi-hardware/assets/4116383/7dc5ccae-da87-45e0-ac61-d305df75b207)
