### ISSUE TITLE
WBO-F103: ID selection pins

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#20]
firmware reads state of two pins in order to figure out CAN index of this specific unit since we support multiple units on the same CAN bus

pull-up, pull-down and floating pins are all supported!

let's have some pads for 0R resistors on PB0 and PB1 for pull-up or pull-down?

![image](https://user-images.githubusercontent.com/48498823/148824595-93ccacc2-dcb2-46ab-bf42-3880a6f5d674.png)

**Comment by dron0gus** [comment]
Implemented on PC13, PC14 pins in https://github.com/rusefi/rusefi-hardware/pull/60
