### ISSUE TITLE
GDI4: board ID

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#200]
looking to have two (maybe three, definitely not four) GDI4 on the same CAN bus network.

* is there any same stm32 pin between rev A and rev C I can use to distinguish between one unit of rev A (with mods if needed) and one unit of rev C (with mods if needed)
* shall we make ^^^ more convenient on rev D?

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/rusefi-hardware/assets/4116383/e25b5ee8-3058-496d-9da4-fe527420c70f)
