### ISSUE TITLE
CAN and control line colors

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#201]
let's mention at least CAN and control line wiring colors right on the schematics

  - pin: 44a
    function: Injector Control 1
    color: green

  - pin: 45a
    function: Injector Control 5
    color: grey

  - pin: 46a
    function: Injector Control 3
    color: blue

  - pin: 47a
    function: Injector Control 6
    color: yellow

  - pin: 48a
    function: Injector Control 2
    color: white

  - pin: 49a
    function: Injector Control 4
    color: orange/brown

  - pin: 52a
    function: CAN High
    color: green

  - pin: 53a
    function: CAN Low
    color: blue

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/rusefi-hardware/assets/4116383/ab708041-049a-4ccb-8521-1156871f089b)
