### ISSUE TITLE
GD4-D does not click pump since microcode expects START6 input not START5

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#208]
i have three boards assembled
all three boards click inj1 when I ground inj1 control line

all boards do not click same injector connected 82/83 and 84/85 when I ground pump control pin 41

**Comment by rusefillc** [comment]
@Qwerty-OFF @NOx-z @mck1117 if I hook signal generator to pin 41 (proteus with self-stimulation) what easily accessible points can I probe on the board with what expected behavior?

**Comment by Qwerty-OFF** [comment]
<img width="1049" alt="image" src="https://github.com/rusefi/rusefi-hardware/assets/4116383/a55b41d2-5d06-4d7d-8351-b3ae8f77d094">
<img width="770" alt="image" src="https://github.com/rusefi/rusefi-hardware/assets/4116383/70aae859-ad91-4e6d-bbbc-6a301ae20701">
<img width="617" alt="image" src="https://github.com/rusefi/rusefi-hardware/assets/4116383/ad6961ca-3d24-4a59-bc6c-84e12f30912e">

**Comment by rusefillc** [comment]
signal reaches point 3
![WhatsApp Image 2023-06-10 at 07 53 03](https://github.com/rusefi/rusefi-hardware/assets/48498823/62207bf7-a7f3-4052-b5fb-be3320931cf8)

**Comment by rusefillc** [comment]
q11 and r19 silence high level

![WhatsApp Image 2023-06-10 at 07 54 12](https://github.com/rusefi/rusefi-hardware/assets/48498823/8d36635d-829d-4eb4-ba90-c2a66702f401)

**Comment by rusefillc** [comment]
q12 r20 silence low level
![WhatsApp Image 2023-06-10 at 07 54 54](https://github.com/rusefi/rusefi-hardware/assets/48498823/354e8915-9b87-4b47-aacb-737452ec6dfe)

**Comment by rusefillc** [comment]
@NOx-z says it's a software issue it wants start6... not start5
I've tested rev A and got pump to click via R60 (start6 input)

**Comment by rusefillc** [comment]
workaround: rev D clicks pump via injector 6 control line
proper fix later: microcode change

no HW changes planned for now

**Comment by rusefillc** [comment]
Change of plan: let's forever stay as is with pump being controlled by START6.
