### ISSUE TITLE
удвоить диаметры двух отверстий на Breakout_154pin_284617-1-Connector

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#218]
мне доступна только 284617-1 вариация разъёма с немного другипи пластиковыми пинами

* удвоить диаметр двух отверстий на футпринте и подвинуть центы как на картинке (с перекрытием старых отверстий)
* скорректировать плату Breakout_154pin_284617-1-Connector
* поменять шёлкографию версии на 0.5

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/rusefi-hardware/assets/99179773/c8870b5f-dda2-4151-a5f5-afe8d631e349)

> * скорректировать плату Breakout_154pin_284617-1-Connector

чего?

**Comment by rusefillc** [comment]
> скорректировать плату Breakout_154pin_284617-1-Connector

ну в смысле трассы подвинуть? как могут я русская языка.

**Comment by Nadezhda-n** [comment]
готово
