### ISSUE TITLE
failing to export gerbers, failing to fail after failing to export gerbers

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#219]
I've created https://github.com/rusefi/rusefi-hardware/blob/main/.github/workflows/create-board.yaml just to export https://github.com/rusefi/rusefi-hardware/tree/main/breakout-boards/Breakout_154pin_284617-1-Connector for now

* it fails to export see error messages at https://github.com/rusefi/rusefi-hardware/actions/runs/5559778665/jobs/10156227662
* job is green even while it has failed

**Comment by rusefillc** [comment]
@chuckwagoncomputing https://github.com/andreika-git/hellen-one/commit/447c4a6fb540b37780b0acbe156d1dfdeb3d21fb and https://github.com/andreika-git/hellen-one/commit/dac43765ba542b6783931610ce00454730465f52 but I am getting closer to the limit of my abilities here :)

**Comment by rusefillc** [comment]
@chuckwagoncomputing I think I've fixed the "fails but does not fail job" part. What am I doing wrong with actual export here?...

**Comment by rusefillc** [comment]
@chuckwagoncomputing I've made some progress looks like VRML export is failing?

**Comment by chuckwagoncomputing** [comment]
It's showing an error, but the ExportVRML_File function is reporting success, and it's outputting a VRML file. Is the file not correct?

**Comment by chuckwagoncomputing** [comment]
When I view the vrml file with https://imagetostl.com/view-vrml-online I get:
![ImageToStl com_hellen88bmw-c-3D(1)](https://github.com/rusefi/rusefi-hardware/assets/1531127/463bd740-6bb3-4d0a-9eff-587e3315c9a5)
We've got some pins hovering over the board:
![ImageToStl com_hellen88bmw-c-3D](https://github.com/rusefi/rusefi-hardware/assets/1531127/fc2f8020-ddf1-4f73-a8e0-58d5a777ee90)
But it was even worse before: (https://github.com/rusefi/hellen88bmw/blob/1b9764f3ea59727ad798e16315f23c75de213dfd/boards/hellen88bmw-c/board/misc/hellen88bmw-c-3D.wrl.gz)
![ImageToStl com_hellen88bmw-c-3D(4)](https://github.com/rusefi/rusefi-hardware/assets/1531127/8b7853b3-0d87-4e2f-bc71-d3cc5a4ab4ed)

**Comment by chuckwagoncomputing** [comment]
I think the problem here is that you're calling ext/hellen-one/bin/gha-commit.sh which doesn't make sense here, and you're calling it from the repo root rather than the directory of the board you're trying to generate gerbers for.
The result is that the files in the gerber/ directory aren't added to the commit.

**Comment by rusefillc** [comment]
@chuckwagoncomputing great point about working dir for gha-commit.sh https://github.com/rusefi/rusefi-hardware/commit/972b37d1d3b69887e014d990000338ca0ea70216

**Comment by rusefillc** [comment]
@chuckwagoncomputing my focus was the assert message I was assuming that it's something bad?

![image](https://github.com/rusefi/rusefi-hardware/assets/48498823/b3acf81a-0184-4af2-85a8-3efa3baa4e7d)

**Comment by rusefillc** [comment]
looks like we do not care about assert message?
