### ISSUE TITLE
GDI4 re-fab rev D

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#225]
S7,S8 | Button_SPST | SMD-2_2.9x3.9x1.7 | SKRKAEE020 C115357

J4,J5 | Conn_01x06 | PinHeader_1x06_P2.54mm_Vertical | 2.54-1*6 C5156615

![image](https://github.com/rusefi/rusefi-hardware/assets/48498823/ad188a0f-6fb4-4f26-81ff-dc13cfdd83e4)

**Comment by Qwerty-OFF** [comment]
C455280
C37208
