### ISSUE TITLE
увеличить верхние отверстия на Breakout_154pin_284617-1-Connector

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#227]
мы недавно успешно удвоили нижние отверстия на Breakout_154pin_284617-1-Connector https://github.com/rusefi/rusefi-hardware/issues/218

оказалось, что на https://github.com/rusefi/hellen154hyundai немного увеличины верхние тоже.

Нужно скопировать размер и расположение верхних с https://github.com/rusefi/hellen154hyundai на Breakout_154pin_284617-1-Connector и сделать ревизию 0.6

**Comment by Nadezhda-n** [comment]
Сделала. После автоматической генерации герберов внутренние слои (лишние, которых нет на плате) удалила вручную

**Comment by rusefillc** [comment]
Алилуя! только версию забыли на плате поменять :)

![image](https://github.com/rusefi/rusefi-hardware/assets/48498823/39e1b52a-6ff4-43a1-9d65-9a3a30440cdf)
