### ISSUE TITLE
hellen-honda-k stim profile/pinout

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#228]
How do I connect https://rusefi.com/docs/pinouts/hellen/hellen-honda-k to https://rusefi.com/docs/pinouts/stim?

IAT goes to https://rusefi.com/docs/pinouts/stim/?connector=main&pin=5B
CLT goes to https://rusefi.com/docs/pinouts/stim/?connector=main&pin=6B

Where should TPS go? Where should MAP go?

**Comment by andreika-git** [comment]
TPS could go to https://rusefi.com/docs/pinouts/stim/?connector=main&pin=7B
MAP could go to https://rusefi.com/docs/pinouts/stim/?connector=main&pin=8B

**Comment by rusefillc** [comment]
```
2023-08-21_01_12_38_547: EngineState: BENCH_TEST Sending CAN bus0 message: ID=770000/l=8 31 0 56 50 0 0 0 0
2023-08-21_01_12_38_547: EngineState: BENCH_TEST Sending CAN bus0 message: ID=770001/l=8 1B 0 0 0 20 4F 2B 62
```

**Comment by rusefillc** [comment]
![16926758845697692266295740299331](https://github.com/rusefi/rusefi-hardware/assets/48498823/a1e403b5-a808-44c3-ba74-89dc175afd77)

**Comment by rusefillc** [comment]
где-то перепутаны IAT и CLT, но где?

на фото видно, что CLT синий на хонде и синий https://rusefi.com/docs/pinouts/stim/?connector=main&pin=6B

```
Processing ID=770001/l=8 1B 0 0 0 20 2B 4F 66
 * BAD channel 5 (CLT): voltage 0.843137280 (raw 43) not in range (1.380596992..1.604477632)
 * BAD channel 6 (IAT): voltage 1.549019712 (raw 79) not in range (0.811403520..0.942982464)
Processing ID=770001/l=8 1B 0 0 0 20 2B 4F 66
 * BAD channel 5 (CLT): voltage 0.843137280 (raw 43) not in range (1.380596992..1.604477632)
 * BAD channel 6 (IAT): voltage 1.549019712 (raw 79) not in range (0.811403520..0.942982464)
```

**Comment by andreika-git** [comment]
![image](https://github.com/rusefi/rusefi-hardware/assets/15104768/7f0db9b5-a4d1-424d-90e0-a2486e607a6c)

**Comment by rusefillc** [comment]
@andreika-git please add "getBoardMetaOutputsCount()" and other parts of the output pattern into honda
