### ISSUE TITLE
re-order GDI4 rev D

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#250]
U6 | MCP6004 | TSSOP-14_4.4x5mm_P0.65mm | TP6004-TRC2485774 1MHz TSSOP-14 Operational Amplifier ROHS | 10 | 1 JLCPCB | Extended | $0.6315 | 9 shortfall
-- | -- | -- | -- | -- | -- | -- | -- | --
Q13 | AOD4185 | TO-252-2 | AOD4185C40089440V 40A 15mΩ@10V,20A P Channel TO-252 MOSFETs ROHS | 10 | 1 JLCPCB | Extended | $0.3182 | 9 shortfall

![image](https://github.com/rusefi/rusefi-hardware/assets/48498823/595c2f00-34a0-4436-a94d-b6162e72a4f1)

**Comment by Qwerty-OFF** [comment]
U6 C50282
