### ISSUE TITLE
mcz33810 test board

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#255]
Looking to make a test board around mcz33810 https://www.nxp.com/products/power-management/smart-switches-and-drivers/low-side-switches/automotive-engine-control-ic:MC33810

26 superseal connector any pinout

* SPI on the connector and also vias to solder wires
* GND/power
* 8 outputs 
* igbts same as https://github.com/rusefi/rusefi-hardware/issues/159

We have footprint ready https://github.com/rusefi/kicad6-libraries/commit/a723b4c5e3fc240597fa57c9205f5f1ac134d35b

**Comment by rusefillc** [comment]
first part of the schematics https://github.com/andreika-git/hellen-one/issues/207#issuecomment-1336519453

**Comment by rusefillc** [comment]
@Qwerty-OFF проводочек откуда куда?

**Comment by Nadezhda-n** [comment]
> first part of the schematics [andreika-git/hellen-one#207 (comment)](https://github.com/andreika-git/hellen-one/issues/207#issuecomment-1336519453)

![image](https://github.com/rusefi/rusefi-hardware/assets/99179773/5e61d148-5873-4047-aa90-3dc2b85635cf)
Эта часть заменяется на https://github.com/rusefi/rusefi-hardware/issues/159 ?
Или на другие какие-то цепи ставить (IGN1/D_IGN1)?
