### ISSUE TITLE
revive tle9104

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#261]
https://github.com/rusefi/rusefi-hardware/tree/main/tle9104-breakout

* convert to kicad 7
* fix paths considering current location
* export BOM and CPL files into "export" folder
* TLE9104 use jlcpcb part number C2650386

**Comment by Nadezhda-n** [comment]
@rusefillc 
Компоненты для сквозного монтажа тоже должны иметь номер LCSC?

**Comment by rusefillc** [comment]
@Nadezhda-n давай попробуем без стресса

**Comment by Nadezhda-n** [comment]
> @Nadezhda-n давай попробуем без стресса

Тогда вроде обновила https://github.com/rusefi/rusefi-hardware/blob/main/tle9104-breakout/export/tle9104-breakout-bom.csv
Посмотри, все ли я поняла верно?

**Comment by rusefillc** [comment]
@Nadezhda-n не вижу placement файла?

**Comment by Nadezhda-n** [comment]
> @Nadezhda-n не вижу placement файла?

потерялся...( но уже найден и в нужной папке!

**Comment by rusefillc** [comment]
@Nadezhda-n у тебя есть VPN или другой способ протестировать возмозность заказа? что-то у меня не принимает файлы ругается на формат

**Comment by Nadezhda-n** [comment]
> @Nadezhda-n у тебя есть VPN или другой способ протестировать возмозность заказа? что-то у меня не принимает файлы ругается на формат

vpn есть, но то ли для Румынии не делают монтаж, то ли что-то не работает... 
Но я помню, что просто файлы не работали, я их по старому примеру отредактировала. Проверь еще раз, пожалуйста
