### ISSUE TITLE
lambda-X2 REV1 A005 LSU4.9 board config

### ISSUE THREAD

**Issue by ggurov** [rusefi/rusefi-hardware#263]
https://github.com/rusefi/rusefi-hardware/tree/main/lambda-x2#esr-measurement-crosstalk-between-channels-rev0-and-rev1

 suggests that for lambda-x2  LSU 4.9 sensor i need to remove : R25 R41 R72 R73, and keep R24 R71 on board. board i received is labeled A005, REV1, 4.9 LSU.  R25 and R72 are still present (these are on the REMOVE list), both R24 and R71 from the KEEP list are present. R71 measures at 18.5k OHM.

what to do ? plug it in  ? remove R25 and R72 ? 

![image](https://github.com/rusefi/rusefi-hardware/assets/2112173/38bff7ec-f6e8-4c15-99c9-30326cd651fb)

![image](https://github.com/rusefi/rusefi-hardware/assets/2112173/9257274e-f7ce-426f-a007-b6a97086effe)

![image](https://github.com/rusefi/rusefi-hardware/assets/2112173/3c4a4991-7e81-4faf-a641-38813f625678)

**Comment by rusefillc** [comment]
@ggurov this looks like mistake on my end - please remove R25 and R72
