### ISSUE TITLE
MX23 18 pin

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#267]
need MX23A18NF1 footprint *FOR ALTIUM DESIGNER*

we have 26 pin sibling used in https://github.com/rusefi/rusefi-hardware/tree/main/wideband-F103 so we shall use consistent file name and location if possible

**Comment by Nadezhda-n** [comment]
> location 

а куда его сохранять?

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/rusefi-hardware/assets/99179773/9f47d207-f461-4ba6-b65a-a2d21e9fce4f)

**Comment by rusefillc** [comment]
@Nadezhda-n в папку https://github.com/rusefi/kicad-libraries-private/tree/master/AD ?

**Comment by Nadezhda-n** [comment]
готово @rusefillc
