### ISSUE TITLE
D1 placement

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#277]
D1 is pretty close to the mounting hole (the alpha had traces going right against the hole, I had to add plastic to guard against the screws I put in to hold the connector , so I was looking at what is near such holes) but it may not be an issue

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/user-attachments/assets/892d11a0-96d4-4fb2-8168-68d09ff9dd0c)
