### ISSUE TITLE
F1 placement

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#278]
F1 the fuse that can commonly blow, is right near the plastic connector and sort of jammed in with other components, this is something that is likely to be replaced when things go awry and melting plastic isnt fun

**Comment by Qwerty-OFF** [comment]
Also https://github.com/andreika-git/hellen-one/issues/393
![image](https://github.com/user-attachments/assets/bd11bf15-dac4-43b0-8b9e-8aaead619c0f)
