### ISSUE TITLE
GDI-4ch FW to read index pin

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#283]
We need provisions for two GDI4 units to share same CANbus

let's have a physical index pin:
* in case of floating/PD we consider index=0
* in case of a pull-up we consider index=1

**Comment by dron0gus** [comment]
https://github.com/rusefi/libfirmware/pull/24

**Comment by dron0gus** [comment]
https://github.com/rusefi/rusefi-hardware/pull/289
