### ISSUE TITLE
START1-START6 controlled by legacy ECU

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#30]
GDI4&GDI6 are hooked to legacy ECU thus

![image](https://user-images.githubusercontent.com/48498823/155245476-9193b6f5-489e-426a-b09a-40826397e128.png)

This will allow us to drive STARTx from a normal lowside output on an ECU.

**Comment by rusefillc** [comment]
@mck1117 ^^^

**Comment by Qwerty-OFF** [comment]
Done
![image](https://user-images.githubusercontent.com/4116383/155350525-5affcb40-f947-4eec-9848-67ac2a794f27.png)
