### ISSUE TITLE
ADC on naked 429 nucleo

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#35]
https://github.com/rusefi/rusefi-hardware/tree/main/digital-inputs/firmware firmware has working serial-over-USB which should print ADC reading

problem: it does not print anything close to 0v or close to 4096 if I GND or +3v on corresponding pins

See https://github.com/rusefi/rusefi-hardware/blob/main/digital-inputs/firmware/adc.cpp

**Comment by rusefillc** [comment]
actual result: I do have _some_ adc values and those do change if I GND or +3v, just not good enough

**Comment by dron0gus** [comment]
@rusefillc is it fixed now?

**Comment by rusefillc** [comment]
yes! one of dramas was about inversion of something
