### ISSUE TITLE
WBO F103 HW status

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#37]
problem 1: op-ams are miss-wired https://rusefi.com/forum/viewtopic.php?p=44220#p44220

problem 2: suggested to use PB6 for heater in order to use HW timer https://github.com/rusefi/wideband/commit/4d736b0d446f9ed16ea0d5c82de8882585170e7b

**Comment by dron0gus** [comment]
Fixed in https://github.com/rusefi/rusefi-hardware/pull/60
