### ISSUE TITLE
WBO: Self-contained VBAT

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#38]
Some maybe many variants of WBO could deal with VBATT on their own

![WhatsApp Image 2022-03-19 at 10 56 05 AM](https://user-images.githubusercontent.com/48498823/159127773-6a452cee-653d-485d-aa27-6bdb84db6bb6.jpeg)

**Comment by mck1117** [comment]
but why? they get vbatt from the ECU for free

**Comment by rusefillc** [comment]
part of evil plan https://github.com/mck1117/wideband/issues/12 and overall detach from ECU

**Comment by dron0gus** [comment]
HW fixed in https://github.com/rusefi/rusefi-hardware/pull/60 (but different ADC channel and divider values)
