### ISSUE TITLE
back side silkscreen

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#43]
Can we please document as much as possible on the back side of the silk?

![image](https://user-images.githubusercontent.com/48498823/159193174-0ebb3588-2d94-4474-ad8a-3f6ad77d8055.png)

**Comment by rusefillc** [comment]
Same on random test points

MOSI/MISO? etc? SWD?

![image](https://user-images.githubusercontent.com/48498823/159193197-288ea52f-9042-4c66-8151-fdf50560b727.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/159346902-7f84884b-3b25-4229-ad58-c109d51b971b.png)
