### ISSUE TITLE
Connect flag1/2, dbg, irq to mcu

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#45]
@mck1117 @NOx-z when do we need "flag1/2, dbg, irq to mcu" connected to MCU?

**Comment by NOx-z** [comment]
Future proofing, for the if/when the microcode may evolve. It is not currently in use, but you may as well have the ability if there are extra pins on the uC available as it is only some extra traces, no additional components needed.

**Comment by rusefillc** [comment]
@Qwerty-OFF please add with 0R jumpers

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/159350385-2083724a-a3ce-4dc1-b66c-5e6d54cb4af0.png)
![image](https://user-images.githubusercontent.com/4116383/159350423-9eb5aa9a-35fb-40d4-9c8c-d482510867fe.png)
