### ISSUE TITLE
BMS for 4 channel LiFePo device

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#5]
Martin wants to race with a lightweight battery (half the acid weight)

safest lithium battery type

**Comment by mmatousek89** [comment]
https://www.ti.com/product/BQ76PL536A

**Comment by mmatousek89** [comment]
device should monitor each cell voltage

trigger alarm/disconect battery when undervoltage or alternator overvoltage

provide cell balancing (discharge) by conecting rezistor to individual cell for proper amount of time

**Comment by OrchardPerformance** [comment]
I don't understand why this is a rusEFI task? 

LiPO racing batteries already exist that have their BMS inside the casing and just bolt into existing systems.
Designed to work with a normal car charging circuit. 

https://jackwebbmotorsport.co.uk/LiFePO4-Lithium-Batteries-c42278020

**Comment by mmatousek89** [comment]
@OrchardPerformance yep there is allso plenty of ecus which already exists like Motec, speeduiono, megasquirt or ecumaster, so why rusefi makes their own ECU?

**Comment by mck1117** [comment]
We have neither the time nor care to do this. If you want to pay me $1000 to do it, I will instead use that to buy you a few off-the-shelf racing lithium batteries. Just not worth bothering.

For example: https://antigravitybatteries.com/
