### ISSUE TITLE
9779 review

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#55]
We have https://github.com/rusefi/rusefi-hardware/tree/main/L9779WD-breakout in kicad5 MRE name

open question: what shall we do with

![WhatsApp Image 2022-03-18 at 4 26 15 PM](https://user-images.githubusercontent.com/48498823/161080073-9bd9e996-14ea-4a55-b59f-63163b00c9df.jpeg)

**Comment by dron0gus** [comment]
OUT_21..OUT24 to OUTA..OUTD of 9779.
FLCP -> SCK of 9779.
Looks like INJ_IN_* and INJ_* are swapped on 9779. INJ_IN_* are logic level signals from STM32 should go to 9779's IN1..IN4.
IN_9..IN_12 nets to IN5..PWM/IN8 inputs of 9779.
OUT_5, OUT_6, OUT_7 to OUT5, OUT6, OUT7 of 9779.

**Comment by dron0gus** [comment]
@rusefillc do we want to replace two discrete ignition drivers (U32, U33 MIC4427) with L9779's integrated ignition pre-drivers?

**Comment by dron0gus** [comment]
![Screenshot from 2022-04-06 15-56-05](https://user-images.githubusercontent.com/28624689/161979622-98dcc88f-4f82-49c8-8107-9d02f5d19b45.png)
Delete.

**Comment by dron0gus** [comment]
Add 0R jumpers (not populate by default) between following nets:
OUT_14 - AV9
OUT_15 - AV8
OUT_16 - AV10
OUT_17 - AV6
Mapping can be adjusted for easy routing.

**Comment by dron0gus** [comment]
9779.OUT_VRS -> CRNK_IN

**Comment by rusefillc** [comment]
@dron0gus yes let's use 9779 features to the most

**Comment by dron0gus** [comment]
@rusefillc ok!
R21, R33, R80, R81 - replace with 100R. Mark populated.
J51, J52, J53, J54 - remove
U32, U33, R122, R123, r124, R125, C78, RN5 - remove.
Ign1_MCU..Ign4_MCU nets - remove.

**Comment by hasl58** [comment]
![изображение_2022-04-13_225438504](https://user-images.githubusercontent.com/17414812/163259630-f5c0976a-2fbd-4e62-84c8-9d3a2656d9d0.png)

?

**Comment by hasl58** [comment]
![изображение_2022-04-13_225515748](https://user-images.githubusercontent.com/17414812/163259718-5f639fe6-b30d-4933-a304-1a4d7094cfc2.png)
?

**Comment by dron0gus** [comment]
OUT_19 OUT_20 are not used outside this sheet, so can be remover.
![Screenshot from 2022-04-14 13-31-08](https://user-images.githubusercontent.com/28624689/163370343-8e0be66d-9193-4b38-9060-41157b9d329e.png)

**Comment by dron0gus** [comment]
As LowSides_1-2 and LowSides_3-4 are now deleted, DFB10 .. DFB 14 and OUT10 .. OUT14 are now no longer used - delete.
OUT8..OUT9 and DFB8..DFB9 are also not used - delete.
WDA_INT to some MCU gpio (if any free left).
