### ISSUE TITLE
F103 board: JDY-33

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#58]
https://github.com/rusefi/alphax-2chan would be a know to work example of JDY-33 usage

JDY-33 is about $1.50 can we place it on the back of the board to keep space small?

**Comment by dron0gus** [comment]
Done for WBOx2 board.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/181455370-3343e73f-a2ff-4c33-b623-96e528074f0b.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/181614525-8b97dea7-c9e4-4c62-9180-b4baad4e0472.png)

**Comment by Ringenium** [comment]
![image](https://user-images.githubusercontent.com/58686541/182035583-fbc30ec9-a432-4cb2-9b84-a03a1f917fc3.png)

Placed the JDY-33 on top of the board
