### ISSUE TITLE
Battery kill switch

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#6]
4 MOSFETs for battery switch
this is to reduce weight
also current measurement

**Comment by mmatousek89** [comment]
https://racespeconline.com/products/msel-solid-state-battery-isolator?variant=13962734862379

**Comment by mmatousek89** [comment]
https://www.ecumaster.com/products/battery-isolator/

**Comment by mmatousek89** [comment]
https://www.infineon.com/dgdl/auirf7749l2.pdf?fileId=5546d462533600a4015355b0aec5140a

4of theese are what ecumaster use

**Comment by mmatousek89** [comment]
https://www.infineon.com/cms/en/product/evaluation-boards/demo_batt_sw_v3/

**Comment by rusefillc** [comment]
Too far D
