### ISSUE TITLE
Remove R41 they say

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#61]
![image](https://user-images.githubusercontent.com/48498823/162625881-7f360341-caa0-4e9f-a182-0ab2bc8d5947.png)

![image](https://user-images.githubusercontent.com/48498823/162625891-55f38343-35c8-455c-81c2-2a992f866d3c.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/162626171-3f31a001-3931-4ddd-9eb2-1c5f7af5a4d9.png)

**Comment by rusefillc** [comment]
Zero urgency will probably remove completely once more tests confirm that we totally absolutely do not need it.

**Comment by Qwerty-OFF** [comment]
Done
