### ISSUE TITLE
how many ADC pins on stm32f4xxZ

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#71]
STM32F407ZGT6?
STM32F427ZGT6?

**Comment by rusefillc** [comment]
407 144 pin

PA0 ADC123_IN0
PA1 ADC123_IN1
PA2 ADC123_IN2
PA3 ADC123_IN3
PA4 ADC12_IN4


PA5
PA6
PA7 ADC12_IN7
PB0 ADC12_IN8
PB1 ADC12_IN9

PC0 ADC123_IN10
PC1
PC2
PC3 ADC123_IN13
PD11  ADC34_IN8 *427*

PF3 ADC3_IN9
PF4 ADC3_IN14
PF5 ADC3_IN15
PF6 ADC3_IN4
PF7 ADC3_IN5

PF8 ADC3_IN6
PF9 ADC3_IN7
PF10 ADC3_IN8

**Comment by mck1117** [comment]
Adc3 is off limits for the way we do things. 16 channels on ADC1/2.
