### ISSUE TITLE
WBO, WBOx2: aux output DAC better that PWM

### ISSUE THREAD

**Issue by dron0gus** [rusefi/rusefi-hardware#72]
If analog outputs are supposed to be used to interface to some ECU (not RE) we need some better solution. 10 to 12 bits.
For gauge it is good enough. May be we just need to change RC filter to some active filter (based on the same buffer opamp).

**Comment by dron0gus** [comment]
[kjn260](https://rusefi.com/forum/memberlist.php?mode=viewprofile&u=1696) suggests MCP4728.

**Comment by Ringenium** [comment]
![image](https://user-images.githubusercontent.com/58686541/182037163-a11d5f2c-f097-4e24-a175-4c56230b0d47.png)

We have activated the microcontroller DAC
