### ISSUE TITLE
GDI4 humming noise

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#84]
GDI4 board is _noisy_

I believe that original PT2001 board made no noise at all?

**Comment by rusefillc** [comment]
same #101

**Comment by mck1117** [comment]
as a fun aside, that means the humming was L2 saturating as the current increased in an uncontrolled manner, which can cause a mechanical thump: https://en.wikipedia.org/wiki/Saturation_(magnetic)
