### ISSUE TITLE
huh? green blinking turns into blue blinking on cranking

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#92]
GDI4 board brinks green before cranking
i crank Passat
GDI4 is now blinking blue and vehicle is not starting :(

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/172518415-519978f9-9020-4158-b244-5f4c510eb7d8.png)

**Comment by mck1117** [comment]
It goes back to green if you power cycle?

**Comment by rusefillc** [comment]
solved by proper soldering of the shunts
