### ISSUE TITLE
GDI4 revisit D10 

### ISSUE THREAD

**Issue by rusefillc** [rusefi/rusefi-hardware#98]
@NOx-z says "while comparing datasheets from current parts vs legacy, D10 - the old part SBR10200CT is a 200v diode vs the new MBRD10100CT is 100v - which is worth having a head note as we brush up against that 100v rail"

@mck1117 @NOx-z @Qwerty-OFF is this OK or not OK?

**Comment by Qwerty-OFF** [comment]
I see MBRD10100CTTR in last BOM version of CommonRail board
![image](https://user-images.githubusercontent.com/4116383/173188628-318e4dee-759a-4831-ae8f-b8d19a754544.png)

**Comment by mck1117** [comment]
I'm actually okay with the ratings on that part - I see no real issue. That diode only sees ~75v max with our 65v rail, and that's enough headroom for me to be happy.
